### ISSUE TITLE
What does "cs life" mean?

### ISSUE THREAD

**Issue by AsakiRain** [godhelph/first-res#1]
RT

**Comment by godhelph** [comment]
because I think if I didn't learn the git/github I weren't cs'er.

**Comment by AsakiRain** [comment]
cs means counter-strike?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "godhelph/first-res"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月3日(星期天) 晚上11:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [godhelph/first-res] What does "cs life" mean? (Issue #1)





 
because I think if I didn't learn the git/github I weren't cs'er.
